AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'db/**/*'

Metrics/BlockLength:
  Enabled: false

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude
