default: &default
  adapter: mysql2
  encoding: utf8
  username: search_admin
  password: search_admin

development:
  <<: *default
  database: search_admin_development

test: &test
  <<: *default
  database: search_admin_test

cucumber:
  <<: *test
