default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: search_admin
  password: search_admin
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: search_admin_development

test: &test
  <<: *default
  database: search_admin_test

cucumber:
  <<: *test
