default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: search_admin_development
  username: search_admin
  password: search_admin

test: &test
  <<: *default
  database: search_admin_test
  username: search_admin
  password: search_admin

cucumber:
  <<: *test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
